--------------------------------------------------------
--  파일이 생성됨 - 월요일-1월-17-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD
--------------------------------------------------------

   CREATE SEQUENCE  "GOCAMPING"."SEQ_BOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REPLY
--------------------------------------------------------

   CREATE SEQUENCE  "GOCAMPING"."SEQ_REPLY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RES
--------------------------------------------------------

   CREATE SEQUENCE  "GOCAMPING"."SEQ_RES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ATTACH_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."ATTACH_TBL" 
   (	"UUID" VARCHAR2(100 BYTE), 
	"UPLOADPATH" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(100 BYTE), 
	"FILETYPE" CHAR(1 BYTE) DEFAULT 'I', 
	"BNO" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Table BOARD_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."BOARD_TBL" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(300 BYTE), 
	"REGDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATEDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"REPLYCNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
 

   COMMENT ON COLUMN "GOCAMPING"."BOARD_TBL"."BNO" IS '글번호';
 
   COMMENT ON COLUMN "GOCAMPING"."BOARD_TBL"."TITLE" IS '글제목';
 
   COMMENT ON COLUMN "GOCAMPING"."BOARD_TBL"."CONTENT" IS '글내용';
 
   COMMENT ON COLUMN "GOCAMPING"."BOARD_TBL"."REGDATE" IS '등록일';
 
   COMMENT ON COLUMN "GOCAMPING"."BOARD_TBL"."UPDATEDATE" IS '수정일';
 
   COMMENT ON COLUMN "GOCAMPING"."BOARD_TBL"."EMAIL" IS '글작성자';
 
   COMMENT ON TABLE "GOCAMPING"."BOARD_TBL"  IS '커뮤니티 게시글';
--------------------------------------------------------
--  DDL for Table CAMP_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."CAMP_TBL" 
   (	"CNO" NUMBER, 
	"CNAME" VARCHAR2(50 BYTE), 
	"SITE" VARCHAR2(100 BYTE), 
	"FACILITY" VARCHAR2(100 BYTE), 
	"FINDCOUNT" NUMBER, 
	"VISITCOUNT" NUMBER, 
	"PRICE" NUMBER, 
	"THEME" VARCHAR2(50 BYTE) DEFAULT '숲', 
	"PHONENUMBER" VARCHAR2(100 BYTE), 
	"LAT" VARCHAR2(50 BYTE), 
	"LNG" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
 

   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."CNO" IS '캠핑장 번호';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."CNAME" IS '캠핑장 이름';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."SITE" IS '캠핑장 위치';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."FACILITY" IS '캠핑장 시설';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."FINDCOUNT" IS '캠핑장 검색 횟수';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."VISITCOUNT" IS '캠핑장 실제 방문 횟수';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."PRICE" IS '캠핑장 가격';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."THEME" IS '테마';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."PHONENUMBER" IS '연락처';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."LAT" IS '위도';
 
   COMMENT ON COLUMN "GOCAMPING"."CAMP_TBL"."LNG" IS '경도';
 
   COMMENT ON TABLE "GOCAMPING"."CAMP_TBL"  IS '캠핑장 테이블(캠핑장 정보)';
--------------------------------------------------------
--  DDL for Table ESTI_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."ESTI_TBL" 
   (	"ENO" NUMBER, 
	"ECONTENT" VARCHAR2(300 BYTE), 
	"NSTAR" NUMBER, 
	"EDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CNO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO" ;
 

   COMMENT ON COLUMN "GOCAMPING"."ESTI_TBL"."ENO" IS '글번호';
 
   COMMENT ON COLUMN "GOCAMPING"."ESTI_TBL"."ECONTENT" IS '글내용';
 
   COMMENT ON COLUMN "GOCAMPING"."ESTI_TBL"."NSTAR" IS '별점';
 
   COMMENT ON COLUMN "GOCAMPING"."ESTI_TBL"."EDATE" IS '등록일';
 
   COMMENT ON COLUMN "GOCAMPING"."ESTI_TBL"."EMAIL" IS '이메일 계정';
 
   COMMENT ON COLUMN "GOCAMPING"."ESTI_TBL"."CNO" IS '캠핑장 번호';
 
   COMMENT ON TABLE "GOCAMPING"."ESTI_TBL"  IS '캠핑장 평가글 테이블';
--------------------------------------------------------
--  DDL for Table MEMBER_AUTH_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."MEMBER_AUTH_TBL" 
   (	"EMAIL" VARCHAR2(50 BYTE), 
	"AUTH" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
 

   COMMENT ON COLUMN "GOCAMPING"."MEMBER_AUTH_TBL"."EMAIL" IS '이메일 계정';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_AUTH_TBL"."AUTH" IS '권한';
 
   COMMENT ON TABLE "GOCAMPING"."MEMBER_AUTH_TBL"  IS '권한테이블';
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."MEMBER_TBL" 
   (	"EMAIL" VARCHAR2(100 BYTE), 
	"EMAIL_CHECK" CHAR(1 BYTE) DEFAULT '0', 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PHONE_NUMBER" VARCHAR2(100 BYTE), 
	"GENDER" CHAR(1 BYTE), 
	"CREATE_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
 

   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."EMAIL" IS '이메일 계정';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."EMAIL_CHECK" IS '이메일 계정 인증 확인여부 0: 미인증 1: 인증';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."PASSWORD" IS '비밀번호';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."NAME" IS '회원 이름';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."PHONE_NUMBER" IS '휴대폰 번호';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."GENDER" IS '성별 0:남자 1:여자 ';
 
   COMMENT ON COLUMN "GOCAMPING"."MEMBER_TBL"."CREATE_DATE" IS '회원가입일';
 
   COMMENT ON TABLE "GOCAMPING"."MEMBER_TBL"  IS '멤버테이블(회원마스터)';
--------------------------------------------------------
--  DDL for Table PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."PERSISTENT_LOGINS" 
   (	"USERNAME" VARCHAR2(64 BYTE), 
	"SERIES" VARCHAR2(64 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"LAST_USED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Table REPLY_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."REPLY_TBL" 
   (	"RNO" NUMBER(10,0), 
	"BNO" NUMBER(10,0), 
	"REPLY" VARCHAR2(1000 BYTE), 
	"REPLYER" VARCHAR2(50 BYTE), 
	"REPLYDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Table RES_TBL
--------------------------------------------------------

  CREATE TABLE "GOCAMPING"."RES_TBL" 
   (	"RNO" NUMBER, 
	"RESDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"PHONE_NUMBER" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"CNO" NUMBER, 
	"REGDATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"RNAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
 

   COMMENT ON COLUMN "GOCAMPING"."RES_TBL"."RNO" IS '예약번호';
 
   COMMENT ON COLUMN "GOCAMPING"."RES_TBL"."RESDATE" IS '예약일';
 
   COMMENT ON COLUMN "GOCAMPING"."RES_TBL"."PHONE_NUMBER" IS '연락처';
 
   COMMENT ON COLUMN "GOCAMPING"."RES_TBL"."EMAIL" IS '이메일 계정';
 
   COMMENT ON COLUMN "GOCAMPING"."RES_TBL"."CNO" IS '캠핑장 번호';
 
   COMMENT ON TABLE "GOCAMPING"."RES_TBL"  IS '캠핑장 예약 테이블';
REM INSERTING into GOCAMPING.ATTACH_TBL
SET DEFINE OFF;
REM INSERTING into GOCAMPING.BOARD_TBL
SET DEFINE OFF;
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (42,'‘차박용 캠핑화재세트’ 출시','‘차박용 캠핑화재세트’ 출시
기사 원문 보기 >>>
https://www.dailysecu.com/news/articleView.html?idxno=126464',to_timestamp('22/01/17 03:22:01.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:01.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (43,'"캠핑은 장비발? 약발도 중요!"…‘벌레물림, 관절·근육 부상, 상처 치료’ 상비약 3','"캠핑은 장비발? 약발도 중요!"…‘벌레물림, 관절·근육 부상, 상처 치료’ 상비약 3
원문보기:
http://www.sportsseoul.com/news/read/1047185?ref=naver#csidxb5e7602fdee3a1895732314e4ad45fb',to_timestamp('22/01/17 03:22:01.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:01.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (44,'레저차량·용품 총출동…캠핑카쇼 내달 3일 부산서 개막','레저차량·용품 총출동…캠핑카쇼 내달 3일 부산서 개막
기사보기 >>>>
https://www.yna.co.kr/view/AKR20210531036000051?input=1195m',to_timestamp('22/01/17 03:22:01.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:01.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (45,'식약처, 나트륨·당류 줄인 캠핑요리 경연대회 개최','식약처, 나트륨·당류 줄인 캠핑요리 경연대회 개최
출처 및 기사보기 >>>>
https://newsis.com/view/?id=NISX20210517_0001443340cID=13107pID=13100',to_timestamp('22/01/17 03:22:08.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:08.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (46,'[인플루언서 프리즘] "요즘 대세는 캠핑" 유튜브 채널도 인기 상승','[인플루언서 프리즘] "요즘 대세는 캠핑" 유튜브 채널도 인기 상승
출처 및 기사 보기 >>>>>
http://news.tf.co.kr/read/livingculture/1854890.htm',to_timestamp('22/01/17 03:22:08.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:08.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (47,'방치됐던 폐교들, ‘차박’ 가능한 캠핑장으로 바뀐다','방치됐던 폐교들, ‘차박’ 가능한 캠핑장으로 바뀐다
기사 원문보기: 
http://www.hani.co.kr/arti/area/honam/985577.html#csidx089ec68e',to_timestamp('22/01/17 03:22:09.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:09.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (48,'도심 속에 캠핑장이 개장했다','도심 속에 캠핑장이 개장했다
출처:프레시안
https://www.pressian.com/pages/articles/2021021816202638479?utm_source=naverutm_medium=search#0DKU',to_timestamp('22/01/17 03:22:56.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:56.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (49,'당신이 캠핑에 빠질 수밖에 없는 이유','당신이 캠핑에 빠질 수밖에 없는 이유
출처 및 내용보기 >>>
http://ch.yes24.com/Article/View/43881',to_timestamp('22/01/17 03:22:56.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:56.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (50,'가을 산행, 캠핑 시 ‘살인진드기’ 요주의','가을 산행, 캠핑 시 ‘살인진드기’ 요주의
가을철 진드기 매개 감염병 ‘SFTS’ 주의보
기사 및 원문보기 >>>>>
https://jhealthmedia.joins.com/article/article_view.asp?pno=22488',to_timestamp('22/01/17 03:22:56.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 03:22:56.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',null);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (0,'[생활정보] 캠핑용품으로 인한 안전사고 예방법','출처 및 기사보기 >>>
    http://www.datasom.co.kr/news/articleView.html?idxno=116797',to_timestamp('22/01/13 15:48:56.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/13 15:48:56.000000000','RR/MM/DD HH24:MI:SSXFF'),'asd',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (10,'‘차박용 캠핑화재세트’ 출시','‘차박용 캠핑화재세트’ 출시
기사 원문 보기 >>>
https://www.dailysecu.com/news/articleView.html?idxno=126464',to_timestamp('22/01/14 15:36:51.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 15:36:51.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (12,'"캠핑은 장비발? 약발도 중요!"…‘벌레물림, 관절·근육 부상, 상처 치료’ 상비약 3','"캠핑은 장비발? 약발도 중요!"…‘벌레물림, 관절·근육 부상, 상처 치료’ 상비약 3
원문보기:
http://www.sportsseoul.com/news/read/1047185?ref=naver#csidxb5e7602fdee3a1895732314e4ad45fb',to_timestamp('22/01/14 15:41:15.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 15:41:15.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (13,'레저차량·용품 총출동…캠핑카쇼 내달 3일 부산서 개막','레저차량·용품 총출동…캠핑카쇼 내달 3일 부산서 개막
기사보기 >>>>
https://www.yna.co.kr/view/AKR20210531036000051?input=1195m',to_timestamp('22/01/14 15:42:45.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 15:42:45.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (14,'식약처, 나트륨·당류 줄인 캠핑요리 경연대회 개최','식약처, 나트륨·당류 줄인 캠핑요리 경연대회 개최
출처 및 기사보기 >>>>
https://newsis.com/view/?id=NISX20210517_000144334013107=1310713100=13100',to_timestamp('22/01/14 15:43:49.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 15:43:49.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (15,'[인플루언서 프리즘] "요즘 대세는 캠핑" 유튜브 채널도 인기 상승','[인플루언서 프리즘] "요즘 대세는 캠핑" 유튜브 채널도 인기 상승
출처 및 기사 보기 >>>>>
http://news.tf.co.kr/read/livingculture/1854890.html',to_timestamp('22/01/14 15:44:58.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 02:16:53.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (16,'방치됐던 폐교들, ‘차박’ 가능한 캠핑장으로 바뀐다','방치됐던 폐교들, ‘차박’ 가능한 캠핑장으로 바뀐다
기사 원문보기: 
http://www.hani.co.kr/arti/area/honam/985577.html#csidx089ec68e',to_timestamp('22/01/14 15:45:45.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 15:45:45.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (17,'도심 속에 캠핑장이 개장했다','도심 속에 캠핑장이 개장했다
출처:프레시안
https://www.pressian.com/pages/articles/2021021816202638479?utm_source=naverutm_medium=search#0DKU',to_timestamp('22/01/14 17:21:54.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 02:47:08.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (18,'당신이 캠핑에 빠질 수밖에 없는 이유','당신이 캠핑에 빠질 수밖에 없는 이유
출처 및 내용보기 >>>
http://ch.yes24.com/Article/View/43881',to_timestamp('22/01/14 17:23:21.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/14 17:23:21.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (19,'가을 산행, 캠핑 시 ‘살인진드기’ 요주의','가을 산행, 캠핑 시 ‘살인진드기’ 요주의
가을철 진드기 매개 감염병 ‘SFTS’ 주의보
기사 및 원문보기 >>>>>
https://jhealthmedia.joins.com/article/article_view.asp?pno=22488',to_timestamp('22/01/14 17:24:05.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/15 06:09:53.000000000','RR/MM/DD HH24:MI:SSXFF'),'admin',0);
Insert into GOCAMPING.BOARD_TBL (BNO,TITLE,CONTENT,REGDATE,UPDATEDATE,EMAIL,REPLYCNT) values (54,'안녕하세요','안녕하세요~^^',to_timestamp('22/01/17 04:41:39.000000000','RR/MM/DD HH24:MI:SSXFF'),to_timestamp('22/01/17 04:42:46.000000000','RR/MM/DD HH24:MI:SSXFF'),'qwe123@naver.com',3);
REM INSERTING into GOCAMPING.CAMP_TBL
SET DEFINE OFF;
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (1,'버들캠핑장','경기도 시흥시 하우로 167','수영장, WIFI, BBQ, 편의점, 전기, 장작판매, 샤워장',0,0,45000,'숲','02-774-9702','37.46854626476885','126.78205927902714');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (2,'민들레캠핑장','경기도 부천시 원미구 심곡3동 352-9번지 5층 우성빌딩','WIFI, BBQ, 편의점, 전기, 장작판매',0,0,40000,'도심','031-655-7384','37.48716176525487','126.77515564740956');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (3,'인천대공원 너나들이캠핑장','인천시 남동구 장수서창동 460','BBQ, 편의점, 전기, 장작판매',0,0,40000,'도심','032-467-2123','37.455121154221644','126.74998610913829');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (4,'아로니움 글램핑','인천 강화군 삼산면 삼산남로 85-11','전기, 와이파이, 온수, 놀이터, 산책로, 운동시설',0,0,40000,'섬','010-6552-8587','37.68784435542553','126.36349889099226');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (5,'은빛물결캠핑장','경기도 가평군 하면 대보리 506-1','전기, 와이파이, 장작판매, 온수, 트렘폴린, 물놀이장, 산책로, 운동시설, 마트, 편의점',0,0,50000,'숲, 강','010-8003-8145','37.80276750252969','127.3659147560098');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (6,'간현관광지 캠핑장','강원도 원주시 지정면 소금산길 26','전기, 와이파이, 온수, 마트, 편의점',0,0,50000,'산, 강','033-731-4088','37.36385625438737','127.83337487021117');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (7,'한송오토캠핑장','경기도 가평군 설악면 묵안리 171-4','전기, 와이파이, 장작판매, 온수, 놀이터, 운동시설',0,0,45000,'산, 숲, 계곡','010-4755-0432','37.59396047659148','127.53355726949523');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (8,'인제 아리캠핑장','강원도 인제군 인제읍 광치령로 306 인제아리캠핑장','전기, 와이파이, 장작판매, 온수, 운동시설',0,0,40000,'산, 계곡','010-3239-7045','38.11639901988735','128.17888889065412');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (9,'밀양 도깨비방망이 캠핑장','경상남도 밀양시 단장면 단장로 1055','전기, 와이파이, 장작판매, 온수, 트렘폴린, 마트, 편의점',0,0,50000,'산','055-355-1300','35.484578487035634','128.85035974427035');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (10,'청석들캠핑장','경상북도 경주시 산내면 대현길 176-9','전기, 장작판매, 온수, 물놀이장, 산책로',0,0,48000,'강','010-9974-1215','35.71793975536294','129.07016676945165');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (11,'하비오토캠핑장','충청남도 태안군 남면 진산1길 277-112','전기, 와이파이, 장작판매, 온수, 물놀이장, 운동시설, 마트, 편의점',0,0,50000,'해변','010-5013-3376','36.72435297776975','126.27245451578635');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (12,'황매산미리내파크 오토캠핑장','경상남도 산청군 차황면 황매산로1138번길 215','전기, 와이파이, 장작판매, 온수, 놀이터, 산책로, 운동시설, 마트, 편의점',0,0,50000,'산','	010-4911-2927','35.47623460576534','127.9635817962846');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (13,'한탄강둘레길캠핑장','경기도 포천시 영북면 소회산길 366','전기, 와이파이, 장작판매, 온수, 놀이터, 운동시설',0,0,50000,'숲, 강','010-2044-8198','38.08056281391693','127.24641134124737');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (14,'한성연수원 야영장','경상북도 문경시 마성면 하내2길 55','전기, 장작판매, 온수, 산책로, 운동시설',0,0,40000,'숲','054-571-2244','36.66458411638138','128.08049071365596');
Insert into GOCAMPING.CAMP_TBL (CNO,CNAME,SITE,FACILITY,FINDCOUNT,VISITCOUNT,PRICE,THEME,PHONENUMBER,LAT,LNG) values (15,'허브하우스 금오산오토캠핑장','경상북도 김천시 아포읍 대성지1길 155','전기, 와이파이, 장작판매, 온수, 트렘폴린, 놀이터, 운동시설',0,0,45000,'숲','0507-1464-3695','36.11751228913858','128.2809628306137');
REM INSERTING into GOCAMPING.ESTI_TBL
SET DEFINE OFF;
REM INSERTING into GOCAMPING.MEMBER_AUTH_TBL
SET DEFINE OFF;
Insert into GOCAMPING.MEMBER_AUTH_TBL (EMAIL,AUTH) values ('user','ROLE_USER');
Insert into GOCAMPING.MEMBER_AUTH_TBL (EMAIL,AUTH) values ('admin','ROLE_ADMIN');

REM INSERTING into GOCAMPING.MEMBER_TBL
SET DEFINE OFF;

Insert into GOCAMPING.MEMBER_TBL (EMAIL,EMAIL_CHECK,PASSWORD,NAME,PHONE_NUMBER,GENDER,CREATE_DATE) values ('admin','0','$2a$10$xPlLauKIa12jOliDXN/XheOnxUhQ3RaEPapDen86IS1wl7JpaJ916','관리자',null,'0',to_date('21/12/29','RR/MM/DD'));
Insert into GOCAMPING.MEMBER_TBL (EMAIL,EMAIL_CHECK,PASSWORD,NAME,PHONE_NUMBER,GENDER,CREATE_DATE) values ('user','0','$2a$10$smtNLnxxe0aFhAyUbQKdpO1wtYfmae5RXeBENl7liiW6QzvD/Hmd2','일반사용자',null,'0',to_date('21/12/29','RR/MM/DD'));

REM INSERTING into GOCAMPING.PERSISTENT_LOGINS
SET DEFINE OFF;
REM INSERTING into GOCAMPING.REPLY_TBL
SET DEFINE OFF;
REM INSERTING into GOCAMPING.RES_TBL
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index BOARD_TBL_BNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."BOARD_TBL_BNO_PK" ON "GOCAMPING"."BOARD_TBL" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index CAMP_TBL_CNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."CAMP_TBL_CNO_PK" ON "GOCAMPING"."CAMP_TBL" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index ESTI_TBL_ENO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."ESTI_TBL_ENO_PK" ON "GOCAMPING"."ESTI_TBL" ("ENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index IDX_REPLY
--------------------------------------------------------

  CREATE INDEX "GOCAMPING"."IDX_REPLY" ON "GOCAMPING"."REPLY_TBL" ("BNO" DESC, "RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index MEMBER_TBL_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."MEMBER_TBL_EMAIL_PK" ON "GOCAMPING"."MEMBER_TBL" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index PK_ATTACH
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."PK_ATTACH" ON "GOCAMPING"."ATTACH_TBL" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."PK_REPLY" ON "GOCAMPING"."REPLY_TBL" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index RES_TBL_RESNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."RES_TBL_RESNO_PK" ON "GOCAMPING"."RES_TBL" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010836
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."SYS_C0010836" ON "GOCAMPING"."PERSISTENT_LOGINS" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index PK_ATTACH
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."PK_ATTACH" ON "GOCAMPING"."ATTACH_TBL" ("UUID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index BOARD_TBL_BNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."BOARD_TBL_BNO_PK" ON "GOCAMPING"."BOARD_TBL" ("BNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index CAMP_TBL_CNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."CAMP_TBL_CNO_PK" ON "GOCAMPING"."CAMP_TBL" ("CNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index ESTI_TBL_ENO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."ESTI_TBL_ENO_PK" ON "GOCAMPING"."ESTI_TBL" ("ENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index MEMBER_TBL_EMAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."MEMBER_TBL_EMAIL_PK" ON "GOCAMPING"."MEMBER_TBL" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010836
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."SYS_C0010836" ON "GOCAMPING"."PERSISTENT_LOGINS" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."PK_REPLY" ON "GOCAMPING"."REPLY_TBL" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index IDX_REPLY
--------------------------------------------------------

  CREATE INDEX "GOCAMPING"."IDX_REPLY" ON "GOCAMPING"."REPLY_TBL" ("BNO" DESC, "RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  DDL for Index RES_TBL_RESNO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GOCAMPING"."RES_TBL_RESNO_PK" ON "GOCAMPING"."RES_TBL" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO" ;
--------------------------------------------------------
--  Constraints for Table ATTACH_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."ATTACH_TBL" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY ("UUID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."ATTACH_TBL" MODIFY ("UUID" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."ATTACH_TBL" MODIFY ("UPLOADPATH" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."ATTACH_TBL" MODIFY ("FILENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BOARD_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."BOARD_TBL" ADD CONSTRAINT "BOARD_TBL_BNO_PK" PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."BOARD_TBL" MODIFY ("TITLE" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."BOARD_TBL" MODIFY ("CONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."BOARD_TBL" MODIFY ("REGDATE" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."BOARD_TBL" MODIFY ("UPDATEDATE" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."BOARD_TBL" MODIFY ("EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAMP_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."CAMP_TBL" ADD CONSTRAINT "CAMP_TBL_CNO_PK" PRIMARY KEY ("CNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."CAMP_TBL" MODIFY ("CNAME" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."CAMP_TBL" MODIFY ("SITE" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."CAMP_TBL" MODIFY ("FACILITY" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."CAMP_TBL" MODIFY ("FINDCOUNT" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."CAMP_TBL" MODIFY ("VISITCOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTI_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."ESTI_TBL" ADD CONSTRAINT "ESTI_TBL_ENO_PK" PRIMARY KEY ("ENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."ESTI_TBL" MODIFY ("ECONTENT" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."ESTI_TBL" MODIFY ("NSTAR" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."ESTI_TBL" MODIFY ("EDATE" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."ESTI_TBL" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."ESTI_TBL" MODIFY ("CNO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."MEMBER_TBL" ADD CONSTRAINT "MEMBER_TBL_EMAIL_CHECK_CK" CHECK (email_check IN ('0', '1')) ENABLE;
 
  ALTER TABLE "GOCAMPING"."MEMBER_TBL" ADD CONSTRAINT "MEMBER_TBL_EMAIL_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."MEMBER_TBL" ADD CONSTRAINT "MEMBER_TBL_GENDER_CK" CHECK (GENDER IN ('0', '1')) ENABLE;
 
  ALTER TABLE "GOCAMPING"."MEMBER_TBL" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."MEMBER_TBL" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSISTENT_LOGINS
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."PERSISTENT_LOGINS" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."PERSISTENT_LOGINS" MODIFY ("TOKEN" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."PERSISTENT_LOGINS" MODIFY ("LAST_USED" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."PERSISTENT_LOGINS" ADD PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLY_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."REPLY_TBL" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."REPLY_TBL" MODIFY ("BNO" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."REPLY_TBL" MODIFY ("REPLY" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."REPLY_TBL" MODIFY ("REPLYER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RES_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."RES_TBL" ADD CONSTRAINT "RES_TBL_RESNO_PK" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MT_CAMPINGGO"  ENABLE;
 
  ALTER TABLE "GOCAMPING"."RES_TBL" MODIFY ("PHONE_NUMBER" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."RES_TBL" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."RES_TBL" MODIFY ("CNO" NOT NULL ENABLE);
 
  ALTER TABLE "GOCAMPING"."RES_TBL" MODIFY ("RESDATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ATTACH_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."ATTACH_TBL" ADD CONSTRAINT "FK_BOARD_ATTACH" FOREIGN KEY ("BNO")
	  REFERENCES "GOCAMPING"."BOARD_TBL" ("BNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."BOARD_TBL" ADD CONSTRAINT "BOARD_TBL_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "GOCAMPING"."MEMBER_TBL" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTI_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."ESTI_TBL" ADD CONSTRAINT "ESTI_TBL_CNO_FK" FOREIGN KEY ("CNO")
	  REFERENCES "GOCAMPING"."CAMP_TBL" ("CNO") ENABLE;
 
  ALTER TABLE "GOCAMPING"."ESTI_TBL" ADD CONSTRAINT "ESTI_TBL_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "GOCAMPING"."MEMBER_TBL" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MEMBER_AUTH_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."MEMBER_AUTH_TBL" ADD CONSTRAINT "MEMBER_AUTH_TBL_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "GOCAMPING"."MEMBER_TBL" ("EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."REPLY_TBL" ADD CONSTRAINT "FK_REPLY_BOARD" FOREIGN KEY ("BNO")
	  REFERENCES "GOCAMPING"."BOARD_TBL" ("BNO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RES_TBL
--------------------------------------------------------

  ALTER TABLE "GOCAMPING"."RES_TBL" ADD CONSTRAINT "RES_TBL_CNO_FK" FOREIGN KEY ("CNO")
	  REFERENCES "GOCAMPING"."CAMP_TBL" ("CNO") ENABLE;
 
  ALTER TABLE "GOCAMPING"."RES_TBL" ADD CONSTRAINT "RES_TBL_EMAIL_FK" FOREIGN KEY ("EMAIL")
	  REFERENCES "GOCAMPING"."MEMBER_TBL" ("EMAIL") ENABLE;
